In [28]:
import numpy as np
import math
from sympy import symbols, Eq, solve

In [29]:
# no of rows are equal to the number of columns.
n = int(input("Enter the number of rows in a matrix"))
tpm = [[0 for x in range (n)] for y in range(n)]
for i in range (n):
    for j in range(n):
        tpm[i][j]=float(input())
print(tpm)

Enter the number of rows in a matrix 3
 0
 0.5
 0.5
 0.5
 0
 0.5
 0
 1
 0


[[0.0, 0.5, 0.5], [0.5, 0.0, 0.5], [0.0, 1.0, 0.0]]


In [30]:
#take input of lambda
lmda=[]
for i in range(n):
    x=int(input("enter the value of lambda"))
    lmda.append(x)
print(lmda)

enter the value of lambda 1
enter the value of lambda 2
enter the value of lambda 3


[1, 2, 3]


In [58]:
#exponential matrix
z_mat=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        if i!=j:    
            z_mat[i][j]=lmda[i]
        
print(z_mat)      
            

[[0. 1. 1.]
 [2. 0. 2.]
 [3. 3. 0.]]


In [59]:
#generator matrix final
g_mat=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        g_mat[i][j]=z_mat[i][j]*tpm[i][j]
        
for i in range(n):
    for j in range(n):
        if i==j:
            g_mat[i][j]=lmda[i]-2*(lmda[i])
print(g_mat)

[[-1.   0.5  0.5]
 [ 1.  -2.   1. ]
 [ 0.   3.  -3. ]]


In [60]:
vals=[]
a=1
for i in range(n):
    for j in range(n):
        vals.append(g_mat[j][i])
print(vals)

l={}
for i in range(0,3*n,n):
    l[i]=vals[i:i+3]
print(l)

[-1.0, 1.0, 0.0, 0.5, -2.0, 3.0, 0.5, 1.0, -3.0]
{0: [-1.0, 1.0, 0.0], 3: [0.5, -2.0, 3.0], 6: [0.5, 1.0, -3.0]}


In [61]:
#uniformized matrix
i=np.identity(n)
l_max=(max(lmda))**(-1)

h_mat=g_mat*l_max
k_mat=i+h_mat
print(k_mat)

[[0.66666667 0.16666667 0.16666667]
 [0.33333333 0.33333333 0.33333333]
 [0.         1.         0.        ]]


In [62]:
# imported the library sympy
# defining symbols used in equations
# or unknown variables
x, y, z = symbols('x,y,z')

# defining equations
eq1 = Eq((x+y+z), 1)
print("Equation 1:")
print(eq1)

eq2 = Eq((l[3][0]*x+l[3][1]*y+l[3][2]*z), 0)
print("Equation 2")
print(eq2)

eq3 = Eq((l[6][0]*x+l[6][1]*y+l[6][2]*z), 0)
print("Equation 3")
print(eq3)

# solving the equation and printing the
# value of unknown variables
print("Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))

Equation 1:
Eq(x + y + z, 1)
Equation 2
Eq(0.5*x - 2.0*y + 3.0*z, 0)
Equation 3
Eq(0.5*x + 1.0*y - 3.0*z, 0)
Values of 3 unknown variable are as follows:
{x: 0.400000000000000, y: 0.400000000000000, z: 0.200000000000000}


In [63]:
tpm1=np.mat(tpm)
pow1=tpm1**36
print(pow1)

[[0.22222222 0.44444444 0.33333333]
 [0.22222222 0.44444444 0.33333333]
 [0.22222222 0.44444444 0.33333333]]


In [66]:
a_mat=np.zeros((n,n))
t=float(input("Enter t value "))
for i in range (n):
    for j in range (n):
        a_mat[i][j]=math.exp(g_mat[i][j]*t)
print(a_mat)

Enter t value  2


[[1.35335283e-01 2.71828183e+00 2.71828183e+00]
 [7.38905610e+00 1.83156389e-02 7.38905610e+00]
 [1.00000000e+00 4.03428793e+02 2.47875218e-03]]
